---
region: 'eu-west-2'

component: 'test'
deployment_identifier: "%{hiera('seed')}"

domain_name: "%{hiera('deployment_identifier')}.infrablocks.click"

subject_alternative_name_1: "%{hiera('deployment_identifier')}-1.infrablocks.click"
subject_alternative_name_2: "%{hiera('deployment_identifier')}-2.infrablocks.click"

public_zone_id: 'Z08829023L5IPIQBJOX63'
private_zone_id: 'Z0211739BXR21FNN139O'
